In [1]:
#!/usr/bin/env python3

import gymnasium as gym
import numpy as np
import random

sarsa_lambtha = __import__('2-sarsa_lambtha').sarsa_lambtha

def set_seed(env, seed=0):
    env.reset(seed=seed)
    np.random.seed(seed)
    random.seed(seed)

env = gym.make('FrozenLake8x8-v1')
set_seed(env, 0)
Q = np.random.uniform(size=(64, 4))
np.set_printoptions(precision=4)

print(sarsa_lambtha(env, Q, 0.9))

[[0.5939 0.605  0.6805 0.5798]
 [0.5721 0.5776 0.6192 0.6942]
 [0.6087 0.6004 0.7354 0.6133]
 [0.6706 0.6354 0.7223 0.6587]
 [0.6482 0.7571 0.6666 0.6166]
 [0.7161 0.6898 0.8691 0.714 ]
 [0.6959 0.8638 0.6768 0.6857]
 [0.7118 0.8854 0.7088 0.7061]
 [0.6071 0.6716 0.605  0.5905]
 [0.6074 0.6083 0.5915 0.6844]
 [0.5969 0.6212 0.6988 0.5741]
 [0.4929 0.5095 0.5925 0.7254]
 [0.6432 0.6636 0.7762 0.6647]
 [0.7079 0.7114 0.7491 0.7092]
 [0.7419 0.8355 0.7271 0.7145]
 [0.7099 0.6346 0.9006 0.6994]
 [0.6662 0.6403 0.6191 0.6272]
 [0.6244 0.6049 0.6467 0.6784]
 [0.7141 0.6006 0.56   0.5567]
 [0.2828 0.1202 0.2961 0.1187]
 [0.4374 0.4289 0.7727 0.4781]
 [0.6865 0.723  0.8322 0.6671]
 [0.7605 0.9185 0.78   0.774 ]
 [0.7596 0.926  0.8646 0.6766]
 [0.6776 0.6374 0.7619 0.612 ]
 [0.8105 0.665  0.6429 0.6962]
 [0.6182 0.6804 0.746  0.6744]
 [0.5483 0.8008 0.6152 0.6648]
 [0.5916 0.5622 0.7997 0.6698]
 [0.8811 0.5813 0.8817 0.6925]
 [0.7989 0.7784 0.7826 0.8925]
 [0.7805 1.0058 0.7466 0.8156]
 [0.7246