In [1]:
#!/usr/bin/env python3

import os
import random
import numpy as np
import tensorflow as tf
RNNEncoder = __import__('0-rnn_encoder').RNNEncoder

SEED = 0

os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_ENABLE_ONEDNN_OPTS']= '0'
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

encoder = RNNEncoder(1024, 128, 256, 32)
print(encoder.batch)
print(encoder.units)
print(type(encoder.embedding))
print(type(encoder.gru))

initial = encoder.initialize_hidden_state()
print(initial)
x = tf.convert_to_tensor(np.random.choice(1024, 320).reshape((32, 10)))
outputs, hidden = encoder(x, initial)
print(outputs)
print(hidden)


2024-09-29 14:41:17.176362: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


32
256
<class 'keras.src.layers.core.embedding.Embedding'>
<class 'keras.src.layers.rnn.gru.GRU'>
tf.Tensor(
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]], shape=(32, 256), dtype=float32)
tf.Tensor(
[[[-1.74142271e-02 -3.89235048e-03 -8.51056259e-03 ...  1.49093680e-02
    4.63607861e-03 -9.50032566e-03]
  [-5.84723428e-04 -3.91376554e-04 -2.93731736e-03 ...  1.15313083e-02
   -7.68443756e-03 -3.75221809e-03]
  [-9.24797822e-03  1.67387016e-02  6.24627667e-03 ...  1.55981155e-02
    2.26214295e-03 -9.24688391e-03]
  ...
  [ 1.34258475e-02  8.30825977e-03 -7.51757936e-04 ...  1.90223102e-04
    1.30655989e-02  2.49108113e-03]
  [ 4.78143198e-03 -8.10729805e-04 -1.00142299e-03 ... -1.56135270e-02
    2.89196125e-03 -3.54668358e-04]
  [ 4.26594587e-03  1.33996160e-04  7.95928389e-03 ...  3.99613846e-03
    4.48268373e-03  1.42817274e-02]]

 [[ 7.52532436e-03 -1.35537540e-03 -1.286