In [1]:
#!/usr/bin/env python3
import os
import random
import numpy as np
import tensorflow as tf
SelfAttention = __import__('1-self_attention').SelfAttention

SEED = 0

os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_ENABLE_ONEDNN_OPTS']= '0'
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

attention = SelfAttention(256)
print(attention.W)
print(attention.U)
print(attention.V)
s_prev = tf.convert_to_tensor(np.random.uniform(size=(32, 256)), dtype='float32')
hidden_states = tf.convert_to_tensor(np.random.uniform(size=(32, 10, 256)), dtype='float32')
context, weights = attention(s_prev, hidden_states)
print(context)
print(weights)

2024-09-29 14:53:00.161230: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


<Dense name=dense, built=False>
<Dense name=dense_1, built=False>
<Dense name=dense_2, built=False>
tf.Tensor(
[[0.5006811  0.35999915 0.5753905  ... 0.8286368  0.5798173  0.5672721 ]
 [0.47350615 0.6248258  0.32858467 ... 0.42682478 0.49858016 0.6724961 ]
 [0.22056103 0.4680409  0.43272105 ... 0.5488377  0.4271424  0.3500102 ]
 ...
 [0.53201735 0.65310127 0.5120029  ... 0.3198923  0.43202806 0.59810686]
 [0.5037616  0.451586   0.4605859  ... 0.43019643 0.581577   0.5190386 ]
 [0.5785484  0.4963132  0.55556387 ... 0.4432511  0.40495306 0.54897803]], shape=(32, 256), dtype=float32)
tf.Tensor(
[[[0.14724822]
  [0.10781322]
  [0.11434453]
  [0.11323991]
  [0.07801075]
  [0.10650861]
  [0.07545591]
  [0.08692006]
  [0.09276024]
  [0.07769856]]

 [[0.10400049]
  [0.07279713]
  [0.09810074]
  [0.07453301]
  [0.12400243]
  [0.10683236]
  [0.11495142]
  [0.07774313]
  [0.09166445]
  [0.13537487]]

 [[0.07755484]
  [0.0852491 ]
  [0.12072365]
  [0.12271   ]
  [0.07241778]
  [0.17065752]
  [0.10