In [1]:
#!/usr/bin/env python3

import os
import random
import numpy as np
import tensorflow as tf
sdp_attention = __import__('5-sdp_attention').sdp_attention

SEED = 0

os.environ['PYTHONHASHSEED'] = str(SEED)
os.environ['TF_ENABLE_ONEDNN_OPTS']= '0'
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

Q = tf.convert_to_tensor(np.random.uniform(size=(50, 10, 256)).astype('float32'))
K = tf.convert_to_tensor(np.random.uniform(size=(50, 15, 256)).astype('float32'))
V = tf.convert_to_tensor(np.random.uniform(size=(50, 15, 512)).astype('float32'))
output, weights = sdp_attention(Q, K, V)
print(output)
print(weights)

2024-09-29 15:22:00.139370: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


tf.Tensor(
[[[0.52602476 0.63305104 0.39105487 ... 0.503818   0.3139783  0.5435243 ]
  [0.53265864 0.63632315 0.38520002 ... 0.5092816  0.32074797 0.5295449 ]
  [0.5256398  0.6435194  0.39035168 ... 0.51243436 0.31304798 0.53604084]
  ...
  [0.5228019  0.64872926 0.39359713 ... 0.5152777  0.31817788 0.5334744 ]
  [0.523515   0.64202905 0.39964774 ... 0.5046137  0.31423992 0.53647566]
  [0.5354594  0.6390406  0.3939686  ... 0.51529115 0.33709148 0.5237254 ]]

 [[0.56073505 0.5006992  0.4356553  ... 0.56711316 0.6240922  0.48981497]
  [0.5641952  0.49763635 0.43044987 ... 0.5685781  0.61222744 0.48184517]
  [0.5606692  0.4981955  0.4321674  ... 0.5569761  0.6272035  0.48412377]
  ...
  [0.57303303 0.5003186  0.4242203  ... 0.56882024 0.61663824 0.49447   ]
  [0.5682367  0.49352264 0.4131574  ... 0.55753684 0.6130289  0.47994372]
  [0.5613553  0.48653772 0.42484856 ... 0.5619513  0.62081414 0.47832364]]

 [[0.7025377  0.6050627  0.4367122  ... 0.42608917 0.54443926 0.37897173]
  [0.699275