In [2]:
#!/usr/bin/env python3

import numpy as np
pdf = __import__('5-pdf').pdf

if __name__ == '__main__':
    np.random.seed(0)
    m = np.array([12, 30, 10])
    S = np.array([[36, -30, 15], [-30, 100, -20], [15, -20, 25]])
    X = np.random.multivariate_normal(m, S, 10000)
    # print(X)
    P = pdf(X, m, S)
    print(P)

[[ 1.13919349 46.10661566  7.0519495 ]
 [-2.01292265 47.35760007 -4.43391461]
 [ 8.96563372 39.59382658  7.51106974]
 ...
 [ 9.05272289 39.85932266  4.47272097]
 [12.39216481 36.88233254  7.6748657 ]
 [11.56731535 12.90689551 15.23323165]]
None
