In [1]:
#!/usr/bin/env python3

import numpy as np
absorbing = __import__('2-absorbing').absorbing

if __name__ == '__main__':
    a = np.eye(2)
    b = np.array([[0.6, 0.4],
                  [0.3, 0.7]])
    c = np.array([[0.25, 0.2, 0.25, 0.3],
                  [0.2, 0.3, 0.2, 0.3],
                  [0.25, 0.25, 0.4, 0.1],
                  [0.3, 0.3, 0.1, 0.3]])
    d = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0, 0.5, 0.2, 0.3],
                  [0, 0, 0.3, 0.5, .2],
                  [0, 0, 0.2, 0.3, 0.5]])
    e = np.array([[1, 0, 0, 0, 0],
                  [0.25, 0.75, 0, 0, 0],
                  [0, 0.1, 0.5, 0.2, 0.2],
                  [0, 0.1, 0.2, 0.5, .2],
                  [0, 0.1, 0.2, 0.2, 0.5]])
    f = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0, 0, 0.5, 0.5],
                  [0, 0.5, 0.5, 0]])
    g = np.array([[1, 0, 0, 0],
                  [0, 1, 0, 0],
                  [0.1, 0, 0.8, 0.1],
                  [0.1, 0.1, 0.4, 0.4]])
    # print(absorbing(a))
    # print(absorbing(b))
    # print(absorbing(c))
    # print(absorbing(d)) 
    # print(absorbing(e))
    # print(absorbing(f))
    print(absorbing(g))

[[1.     0.     0.     0.    ]
 [0.     1.     0.     0.    ]
 [0.3408 0.0336 0.52   0.1056]
 [0.3072 0.1728 0.4224 0.0976]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0. ]
 [0.1 0.  0.8 0.1]
 [0.1 0.1 0.4 0.4]]
True
