In [1]:
#!/usr/bin/env python3

import numpy as np
# forward = __import__('3-forward').forward

if __name__ == '__main__':
    np.random.seed(1)
    Emission = np.array([[0.90, 0.10, 0.00, 0.00, 0.00, 0.00],
                         [0.40, 0.50, 0.10, 0.00, 0.00, 0.00],
                         [0.00, 0.25, 0.50, 0.25, 0.00, 0.00],
                         [0.00, 0.00, 0.05, 0.70, 0.15, 0.10],
                         [0.00, 0.00, 0.00, 0.20, 0.50, 0.30]])
    Transition = np.array([[0.60, 0.39, 0.01, 0.00, 0.00],
                           [0.20, 0.50, 0.30, 0.00, 0.00],
                           [0.01, 0.24, 0.50, 0.24, 0.01],
                           [0.00, 0.00, 0.15, 0.70, 0.15],
                           [0.00, 0.00, 0.01, 0.39, 0.60]])
    Initial = np.array([0.05, 0.20, 0.50, 0.20, 0.05])
    Hidden = [np.random.choice(5, p=Initial)]
    for _ in range(364):
        Hidden.append(np.random.choice(5, p=Transition[Hidden[-1]]))
    Hidden = np.array(Hidden)
    Observations = []
    for s in Hidden:
        Observations.append(np.random.choice(6, p=Emission[s]))
    Observations = np.array(Observations)
    print(Transition)
    print(Emission)
    print(Initial)
    print(Observations)
    # P, F = forward(Observations, Emission, Transition, Initial.reshape((-1, 1)))
    # print(P)
    # print(F)

[[0.6  0.39 0.01 0.   0.  ]
 [0.2  0.5  0.3  0.   0.  ]
 [0.01 0.24 0.5  0.24 0.01]
 [0.   0.   0.15 0.7  0.15]
 [0.   0.   0.01 0.39 0.6 ]]
[[0.9  0.1  0.   0.   0.   0.  ]
 [0.4  0.5  0.1  0.   0.   0.  ]
 [0.   0.25 0.5  0.25 0.   0.  ]
 [0.   0.   0.05 0.7  0.15 0.1 ]
 [0.   0.   0.   0.2  0.5  0.3 ]]
[0.05 0.2  0.5  0.2  0.05]
